version: "3.8"

networks:
  go-i-prod:

services:
  nginx_backend_prod:
    image: nginx:stable
    container_name: ${APP_NAME}_nginx
    restart: unless-stopped
    ports:
      - "9091:80"
    links:
      - go_backend_prod
    volumes:
      - ~/Program/go/deployments/docker/nginx/site-prod.conf:/etc/nginx/conf.d/default.conf:rw
      - ~/Program/go/deployments/docker/logs/nginx:/var/logs/nginx:rw
    depends_on:
      - go_backend_prod
    networks:
      - go-i-prod
  go_backend_prod:
    image: ${APP_IMAGE_PROD}:${APP_IMAGE_PROD_TAG}
    container_name: ${APP_NAME}_go
    restart: unless-stopped
    volumes:
      - ~/Program/go/.env:/app/.env:rw
    environment:
      DB_HOST: mongodb_backend_prod
      REDIS_HOST: redis_backend_prod
    depends_on:
      - mongodb_backend_prod
      - redis_backend_prod
    networks:
      - go-i-prod
  mongodb_backend_prod:
    image: mongo:latest
    container_name: ${APP_NAME}_mongodb
    restart: unless-stopped
    volumes:
      - ~/Program/go/deployments/docker/mongodb:/data/db:rw
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    networks:
      - go-i-prod
  redis_backend_prod:
    image: redis:latest
    container_name: ${APP_NAME}_redis
    restart: unless-stopped
    volumes:
      - ~/Program/go/deployments/docker/redis:/data:rw
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}  
    command: ["redis-server", "--appendonly", "no", "--maxmemory", "500mb", "--maxmemory-policy", "allkeys-lru"]
    networks:
      - go-i-prod
  minio_backend_prod:
    image: bitnami/minio:latest
    container_name: ${APP_NAME}_minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      -  minio_data:/bitnami/minio:rw
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASS}
    command: ["minio", "server", "/data", "--console-address", ":9001"]
    networks:
      - go-i-prod  

volumes:
  minio_data:      